### ISSUE TITLE
Allow user to specify constraint matrix + dir + rhs in A input

### ISSUE THREAD

**Issue by ramnathv** [alteryx/AlteryxPrescriptive#12]
We split the constraint matrix and dir + rhs into two inputs to allow for sparse matrices. However, for the Annies of the world, who would mostly input dense matrices, it makes sense to allow them to combine the two into a single input. This was the original design that @kuol put together.

To support this, we would have to add logic to `constructModel.matrix_mode` that will construct the OP object based on the input structure.

**Comment by ramnathv** [comment]
I think this is already done. @kuol correct me if I am wrong and I will reopen this issue.

**Comment by kuol** [comment]
yep

**Comment by ramnathv** [comment]
Thanks.
