### ISSUE TITLE
Manual input wrong results

### ISSUE THREAD

**Issue by kuol** [alteryx/AlteryxPrescriptive#14]
The manual input example in `Supporting_Macros/tests` is wrong.  With inputs: `x1`, `x2`, `x3` in specification, the output has 4 variables instead. It is still using the default file for the file input mode:  `getSampleData("lp_example.lp")`

**Comment by kuol** [comment]
My bad: I forgot to update `AlteryxPrescriptive` and `AlteryxRhleper`. It works fine now.

**Comment by ramnathv** [comment]
Cool.
