### ISSUE TITLE
Change output from constructModel

### ISSUE THREAD

**Issue by kuol** [alteryx/AlteryxPrescriptive#8]
The output from the generic function `constructModel` is a `OP` object defined in package `ROI`. The limitations of this output is that it doesn't return important information such as:

- Objective variable names
- Constraint names

Although it doesn't affect solving the underline optimization problems, but in general, I believe we do want to have:

- Preserve the objective and constraint names
- This is especially true for sensitivity analysis, since we want to refer to the column(objective variable) and row(constraint) with a name. This is also a requirement to use `glpkAPI` interface.

**Comment by ramnathv** [comment]
I think this is done as well. Closing it. @kuol reopen if you think this is incomplete.

**Comment by kuol** [comment]
agreed.

**Comment by ramnathv** [comment]
Thanks.
